
services:
  web:
    build: .
    command: bash -c "./wait-for-db.sh python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=integrador.settings
      - DB_HOST=db
    depends_on:
      - db
    
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=integrador
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"

volumes:
  postgres_data: