name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Ckeck Repo
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOkEN}}
      

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER}}/integrador-tungtungtungsahur:latest
            ${{ secrets.DOCKERHUB_USER}}/integrador:${{ github.sha }}

      